#!/bin/bash

# download rust
RUST_TOOLCHAIN="nightly"

set +e
rustup target add --toolchain ${RUST_TOOLCHAIN} wasm32-unknown-unknown && \
cargo  +${RUST_TOOLCHAIN} build --target wasm32-unknown-unknown --release --verbose

# build the wasm
wasm-pack build --target nodejs